services:
  mongo-service:
    build:
      context: .
      dockerfile: mongo.Dockerfile
    container_name: mongo-ct
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    networks:
      - rede-app
  mongo-express-service:
    build:
      context: .
      dockerfile: mongo-express.Dockerfile
    container_name: mongo-express-ct
    ports:
      - 8081:8081
    networks:
      - rede-app
  node1:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: node1
    ports:
      - 3000:3000
    networks:
      - rede-app
    depends_on:
      - mongo-service
  node2:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: node2
    ports:
      - 3001:3000
    networks:
      - rede-app
    depends_on:
      - mongo-service
  node3:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: node3
    ports:
      - 3002:3000
    networks:
      - rede-app
    depends_on:
      - mongo-service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-ct
    ports:
      - 80:80
    networks:
      - rede-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node1
      - node2
      - node3
volumes:
  mongo-volume:
networks:
  rede-app:
    driver: bridge